### ISSUE TITLE
Broken pipe in validate_all.sh

### ISSUE THREAD

**Issue by kwatsen** [ietf-tools/rfcfold#10]
On MacOS 10.15.5 (Catalina).

On`master`, running `validate-all.sh` produces this output:
```
starting tests for -h/--help options...../rfcfold: line 47: printf: write error: Broken pipe
okay.
starting tests for -V/--version options...okay.
<snip/>
```

Digging I ran the commands manually (notice different line numbers: 47, 49, 50):
```
$ ../rfcfold -h | grep -Fq 'Usage:' || failed_test
../rfcfold: line 50: printf: write error: Broken pipe

$ ../rfcfold --help | grep -Fq 'Usage:' || failed_test
../rfcfold: line 47: printf: write error: Broken pipe
```

Similarly, but without the last pipe (note: these are back-to-back runs, sometime they work, sometimes broken pipe):
```
$ ../rfcfold -h | grep -Fq 'Usage:'
$ ../rfcfold -h | grep -Fq 'Usage:'
../rfcfold: line 49: printf: write error: Broken pipe
$ ../rfcfold -h | grep -Fq 'Usage:'
../rfcfold: line 50: printf: write error: Broken pipe
$ ../rfcfold -h | grep -Fq 'Usage:'
$ ../rfcfold -h | grep -Fq 'Usage:'
../rfcfold: line 50: printf: write error: Broken pipe
$ ../rfcfold -h | grep -Fq 'Usage:'
$ echo $?
0
$ ../rfcfold -h | grep -Fq 'Usage:'
$ ../rfcfold -h | grep -Fq 'Usage:'
$ ../rfcfold -h | grep -Fq 'Usage:'
../rfcfold: line 47: printf: write error: Broken pipe
$ echo $?
0
```

One more time, but without any pipes:
```
This worked, no issues.
```

Adding back the last pipe, but removing the "q" option (these all worked, so something to do with 'q'?):
```
$ ../rfcfold -h | grep -F 'Usage:'
Usage: rfcfold [-h] [-d] [-q] [-s <strategy>] [-c <col>] [-r] -i <infile> -o <outfile>
$ ../rfcfold -h | grep -F 'Usage:'
Usage: rfcfold [-h] [-d] [-q] [-s <strategy>] [-c <col>] [-r] -i <infile> -o <outfile>
$ ../rfcfold -h | grep -F 'Usage:'
Usage: rfcfold [-h] [-d] [-q] [-s <strategy>] [-c <col>] [-r] -i <infile> -o <outfile>
$ ../rfcfold -h | grep -F 'Usage:'
Usage: rfcfold [-h] [-d] [-q] [-s <strategy>] [-c <col>] [-r] -i <infile> -o <outfile>
```

**Comment by auerswal** [comment]
Yes, this most likely has to do with the `-q` option of `grep`.

With the `-q` option, grep exits as soon as it has matched a line. Without, it reads all input so that it can output *every* matched line. Thus it seems possible for `grep -q` to exit before `rfcfold` has started all `printf` processes that write help output. This is not a problem since not all data written by `printf` is needed by `grep` to determine it matched at least one input line from the help output. Since this is a timing issue (e.g., when is a given process scheduled to run, when is data written into the pipe buffer, how much is written before the reading process is scheduled, and so on) it is expected to see different line numbers associated with *Broken pipe* error messages.

This behaviour is explicitly stated in the GNU grep manual page:

```
$ man grep | section ' -q,'
       -q, --quiet, --silent
              Quiet;  do  not  write  anything  to  standard   output.    Exit
              immediately  with  zero status if any match is found, even if an
              error was detected.  Also see the -s or --no-messages option.
```

POSIX does not specify if `-q` results in an early exit or not:

> -q
> Quiet. Nothing shall be written to the standard output, regardless of matching lines. Exit with zero status if an input line is selected.

(from https://pubs.opengroup.org/onlinepubs/9699919799/utilities/grep.html#tag_20_55)

I have just tested on Ubuntu GNU/Linux with GNU grep version 3.1:

Early exit with `-q`:

```
$ time (for i in {1..20}; do echo $i; sleep 1; done) | grep -Fq 5

real    0m5,021s
user    0m0,010s
sys     0m0,015s

```

Reading all data without `-q`:

```
~$ time (for i in {1..20}; do echo $i; sleep 1; done) | grep -F 5
5
15

real    0m20,067s
user    0m0,037s
sys     0m0,038s
```

As such I think this is not a real problem, but the behaviour should be masked to avoid chasing this spurious issue again in the future.

I suggest to ignore the *broken pipe* messages by redirecting STDERR of `rfcfold` to `/dev/null` for these two tests.

**Comment by auerswal** [comment]
I have created pull request #11 to implement the above suggestion.

**Comment by auerswal** [comment]
I'll go ahead and pull #11 to fix this issue.
